name: Run reproduction
on: [push, pull_request]

jobs:
  run:
    name: Run
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0

      - name: Check file existence
        id: check_files_1
        uses: andstor/file-existence-action@v1
        with:
          files: "run.sh"

      - name: Run
        if: steps.check_files_1.outputs.files_exists == 'true'
        run: |
          if [ -f run.sh ] ; then
            echo $'------------\n------------\n\n\n'
            bash ./run.sh
          fi

      - name: Upload Results
        uses: actions/upload-artifact@v3
        with:
            name: typedoc-output
            path: docs
