name: Run reproduction
on: [push]

jobs:
  run:
    name: Run
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout
        id: checkout

      - name: Run
        uses: ./.github/runner
        id: run
