name: Run reproduction
on: [push]

jobs:
  run:
    name: Run
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0
      - name: Build runner
        uses: ./.github/runner
        with:
          entrypoint: ["/bin/bash", "-l", "-c", "echo Built"]
      - name: Run
        uses: ./.github/runner
        with:
          entrypoint: ["/bin/bash", "-l", "-c", "/bin/bash ./run.sh"]
